import { APP_ROUTES, activityRoute } from '@/lib/routes';
import type { CustomerNotificationItem } from '@/types/notifications';

export const CUSTOMER_NOTIFICATIONS: CustomerNotificationItem[] = [
  {
    id: 'notif-apt-004-confirmed',
    actionKey: 'openActivity',
    body: 'Jadwal pijat laktasi hari Senin pukul 08:00 WIB sudah dikonfirmasi. Pastikan detail alamat dan nomor aktif tetap siap.',
    href: activityRoute('apt-004'),
    isUnreadByDefault: true,
    section: 'today',
    timeLabel: '5 menit lalu',
    title: 'Jadwal kunjungan Anda sudah dikonfirmasi',
    type: 'appointment',
  },
  {
    id: 'notif-apt-005-message',
    actionKey: 'replyNow',
    body: 'Profesional mengirim follow-up singkat untuk sesi yang sedang berjalan dan meminta konfirmasi kebutuhan tambahan.',
    href: activityRoute('apt-005'),
    isUnreadByDefault: true,
    section: 'today',
    timeLabel: '18 menit lalu',
    title: 'Ada balasan baru dari profesional',
    type: 'message',
  },
  {
    id: 'notif-apt-002-payment',
    actionKey: 'completePayment',
    body: 'Selesaikan pembayaran Rp 120.000 agar slot konsultasi Hari ini, 15:00 WIB tetap aman dan tidak dilepas otomatis.',
    href: activityRoute('apt-002'),
    isUnreadByDefault: true,
    section: 'today',
    timeLabel: '42 menit lalu',
    title: 'Pembayaran masih menunggu',
    type: 'payment',
  },
  {
    id: 'notif-profile-preferences',
    actionKey: 'openProfile',
    body: 'Tambahkan preferensi keluarga, catatan postpartum, dan kontak darurat agar tindak lanjut layanan lebih rapi.',
    href: APP_ROUTES.profile,
    isUnreadByDefault: false,
    section: 'earlier',
    timeLabel: 'Kemarin',
    title: 'Lengkapi detail profil customer',
    type: 'account',
  },
  {
    id: 'notif-apt-006-review',
    actionKey: 'leaveReview',
    body: 'Sesi home visit kemarin sudah selesai. Bagikan ulasan singkat supaya riwayat perawatan keluarga tetap lengkap.',
    href: activityRoute('apt-006'),
    isUnreadByDefault: false,
    section: 'earlier',
    timeLabel: 'Kemarin',
    title: 'Saatnya memberi ulasan layanan',
    type: 'appointment',
  },
];
