#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '..', '..');
const rawName = process.argv[2];

if (!rawName) {
  console.error('Usage: npm run platform:scaffold -- <platform-slug> [port]');
  process.exit(1);
}

const slug = rawName
  .trim()
  .toLowerCase()
  .replace(/[^a-z0-9-]/g, '-');
const displayName = slug
  .split('-')
  .filter(Boolean)
  .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
  .join('');
const port = Number(process.argv[3] || 3010);
const appDir = path.join(repoRoot, 'apps', slug);

if (fs.existsSync(appDir)) {
  console.error(`App ${slug} already exists at ${appDir}`);
  process.exit(1);
}

const files = new Map([
  [
    path.join(appDir, 'package.json'),
    JSON.stringify(
      {
        name: `@marketplace/${slug}`,
        version: '0.0.0-private',
        private: true,
        scripts: {
          build: 'next build',
          dev: `next dev -p ${port}`,
          lint: 'biome ci .',
          start: `next start -p ${port}`,
          test: 'node --test',
          typecheck: 'rm -f tsconfig.tsbuildinfo && next typegen && tsc --noEmit',
        },
        dependencies: {
          '@marketplace/marketplace-core': '0.0.0-private',
          '@marketplace/platform-config': '0.0.0-private',
          '@marketplace/ui': '0.0.0-private',
          '@marketplace/web': '0.0.0-private',
          'framer-motion': '^12.38.0',
          next: '16.1.6',
          react: '19.2.4',
          'react-dom': '19.2.4',
        },
        devDependencies: {
          '@tailwindcss/postcss': '^4',
          '@types/node': '^20',
          '@types/react': '^19',
          '@types/react-dom': '^19',
          tailwindcss: '^4',
          typescript: '^5',
        },
      },
      null,
      2,
    ),
  ],
  [
    path.join(appDir, 'next.config.ts'),
    `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  allowedDevOrigins: ['admin.lvh.me', '${slug}.lvh.me', 'localhost'],
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,
  output: 'standalone',
  typedRoutes: true,
  transpilePackages: ['@marketplace/marketplace-core', '@marketplace/platform-config', '@marketplace/sdk', '@marketplace/ui', '@marketplace/web'],
};

export default nextConfig;
`,
  ],
  [
    path.join(appDir, 'postcss.config.mjs'),
    `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`,
  ],
  [
    path.join(appDir, 'tsconfig.json'),
    `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "allowArbitraryExtensions": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
  ],
  [
    path.join(appDir, 'next-env.d.ts'),
    `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Next.js.
`,
  ],
  [
    path.join(appDir, '.env.example'),
    `NEXT_PUBLIC_SITE_URL=http://${slug}.lvh.me:${port}
NEXT_PUBLIC_API_BASE_URL=http://api.lvh.me:8080/api/v1
`,
  ],
  [
    path.join(appDir, 'src/app/globals.css'),
    `@import "tailwindcss";
@source "../../../../packages/ui/src";
@source "../../../../packages/web/src";
@import "@marketplace/ui/system.css";

body {
  margin: 0;
}
`,
  ],
  [
    path.join(appDir, 'src/app/layout.tsx'),
    `import { themeStyleVariables } from '@marketplace/ui/foundations';
import { appFontClassName } from '@marketplace/web/fonts';
import { resolvePlatformContext } from '@marketplace/web/server';
import './globals.css';

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const platform = await resolvePlatformContext('${slug}' as never);

  return (
    <html lang="id">
      <body className={appFontClassName} style={themeStyleVariables(platform.theme)}>{children}</body>
    </html>
  );
}
`,
  ],
  [
    path.join(appDir, 'src/app/page.tsx'),
    `import { redirect } from 'next/navigation';

export default function RootPage() {
  redirect('/id');
}
`,
  ],
  [
    path.join(appDir, 'src/proxy.ts'),
    `import { NextRequest, NextResponse } from 'next/server';
import { computeLocalHostRedirect } from '@marketplace/web/local-host-redirect';

export function proxy(request: NextRequest) {
  const host = request.headers.get('x-forwarded-host') ?? request.headers.get('host') ?? request.nextUrl.host;
  const currentUrl = new URL(\`\${request.nextUrl.pathname}\${request.nextUrl.search}\`, \`\${request.nextUrl.protocol}//\${host}\`);
  const redirectUrl = computeLocalHostRedirect(currentUrl.toString(), process.env.NEXT_PUBLIC_SITE_URL);
  if (redirectUrl) {
    return NextResponse.redirect(redirectUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml).*)'],
};
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/layout.tsx'),
    `import { createPlatformMetadata } from '@marketplace/web/platform';
import { resolvePlatformContext } from '@marketplace/web/server';

export async function generateMetadata(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, platform] = await Promise.all([props.params, resolvePlatformContext('${slug}' as never)]);
  return createPlatformMetadata(platform, locale);
}

export default async function PlatformLocaleLayout({ children }: { children: React.ReactNode }) {
  return children;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/page.tsx'),
    `import { PlatformHomePage } from '@marketplace/web/public/home-page';

export default async function LocalizedHomePage(props: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;
  return <PlatformHomePage locale={locale} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/explore/page.tsx'),
    `import { PlatformExplorePage } from '@marketplace/web/public/explore-page';

export default async function ExplorePageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;
  return <PlatformExplorePage locale={locale} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/services/page.tsx'),
    `import { PlatformServicesPage } from '@marketplace/web/public/services-page';

export default async function ServicesPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;
  return <PlatformServicesPage locale={locale} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/p/[slug]/page.tsx'),
    `import { PlatformProfessionalDetailPage } from '@marketplace/web/public/professional-detail-page';

export default async function ProfessionalDetailPageRoute(props: {
  params: Promise<{ locale: string; slug: string }>;
}) {
  const { locale, slug } = await props.params;
  return <PlatformProfessionalDetailPage locale={locale} platformId={'${slug}' as never} slug={slug} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/s/[slug]/page.tsx'),
    `import { PlatformOfferingDetailPage } from '@marketplace/web/public/offering-detail-page';

export default async function OfferingDetailPageRoute(props: {
  params: Promise<{ locale: string; slug: string }>;
}) {
  const { locale, slug } = await props.params;
  return <PlatformOfferingDetailPage locale={locale} platformId={'${slug}' as never} slug={slug} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/login/page.tsx'),
    `import { ViewerAuthPage } from '@marketplace/web/auth/viewer-auth-page';
import { createLocalizedPath } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function LoginPage(props: {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ next?: string }>;
}) {
  const [{ locale }, searchParams, session] = await Promise.all([
    props.params,
    props.searchParams,
    fetchViewerSessionServer(),
  ]);

  return (
    <ViewerAuthPage
      defaultNextPath={searchParams.next || createLocalizedPath(locale)}
      initialSession={session}
      locale={locale}
      mode="login"
      platformId={'${slug}' as never}
    />
  );
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/register/page.tsx'),
    `import { ViewerAuthPage } from '@marketplace/web/auth/viewer-auth-page';
import { createLocalizedPath } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function RegisterPage(props: {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ next?: string }>;
}) {
  const [{ locale }, searchParams, session] = await Promise.all([
    props.params,
    props.searchParams,
    fetchViewerSessionServer(),
  ]);

  return (
    <ViewerAuthPage
      defaultNextPath={searchParams.next || createLocalizedPath(locale)}
      initialSession={session}
      locale={locale}
      mode="register"
      platformId={'${slug}' as never}
    />
  );
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/forgot-password/page.tsx'),
    `import { ViewerAuthPage } from '@marketplace/web/auth/viewer-auth-page';
import { createLocalizedPath } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ForgotPasswordPage(props: {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ next?: string }>;
}) {
  const [{ locale }, searchParams, session] = await Promise.all([
    props.params,
    props.searchParams,
    fetchViewerSessionServer(),
  ]);

  return (
    <ViewerAuthPage
      defaultNextPath={searchParams.next || createLocalizedPath(locale)}
      initialSession={session}
      locale={locale}
      mode="forgot-password"
      platformId={'${slug}' as never}
    />
  );
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/orders/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { OrdersPage } from '@marketplace/web/customer/orders-page';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function OrdersPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const platformId = '${slug}' as never;
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/orders'), getServicePlatformOrigin(platformId));

  return <OrdersPage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={platformId} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/orders/[orderId]/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { CustomerOrderDetailPage } from '@marketplace/web/customer/order-detail-page';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function OrderDetailPageRoute(props: {
  params: Promise<{ locale: string; orderId: string }>;
}) {
  const [{ locale, orderId }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, \`/orders/\${orderId}\`), getServicePlatformOrigin('${slug}' as never));

  return <CustomerOrderDetailPage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} orderId={orderId} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/profile/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { CustomerProfilePage } from '@marketplace/web/customer/profile-page';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfilePageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/profile'), getServicePlatformOrigin('${slug}' as never));

  return <CustomerProfilePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/notifications/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { CustomerNotificationsPage } from '@marketplace/web/customer/notifications-page';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function NotificationsPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/notifications'), getServicePlatformOrigin('${slug}' as never));

  return <CustomerNotificationsPage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/support/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { CustomerSupportPage } from '@marketplace/web/customer/support-page';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function SupportPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/support'), getServicePlatformOrigin('${slug}' as never));

  return <CustomerSupportPage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/apply/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalApplyPage } from '@marketplace/web/professional/apply-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalApplyPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/apply'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalApplyPage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="overview" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/orders/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardOrdersPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/orders'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="orders" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/offerings/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardOfferingsPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/offerings'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="offerings" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/portfolio/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardPortfolioPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/portfolio'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="portfolio" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/trust/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardTrustPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/trust'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="trust" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/coverage/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardCoveragePageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/coverage'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="coverage" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/availability/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardAvailabilityPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/availability'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="availability" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/notifications/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardNotificationsPageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/notifications'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="notifications" />;
}
`,
  ],
  [
    path.join(appDir, 'src/app/[locale]/professionals/dashboard/profile/page.tsx'),
    `import { getServicePlatformOrigin } from '@marketplace/platform-config';
import { createLocalizedPath, createPlatformAppUrl, createPlatformAuthUrl } from '@marketplace/web/platform';
import { ProfessionalWorkspacePage } from '@marketplace/web/professional/workspace-page';
import { fetchViewerSessionServer } from '@marketplace/web/server';

export default async function ProfessionalDashboardProfilePageRoute(props: {
  params: Promise<{ locale: string }>;
}) {
  const [{ locale }, session] = await Promise.all([props.params, fetchViewerSessionServer()]);
  const nextPath = createPlatformAppUrl(createLocalizedPath(locale, '/professionals/dashboard/profile'), getServicePlatformOrigin('${slug}' as never));

  return <ProfessionalWorkspacePage authHref={createPlatformAuthUrl(nextPath, locale)} initialSession={session} locale={locale} platformId={'${slug}' as never} section="profile" />;
}
`,
  ],
  [
    path.join(repoRoot, 'config/platform-stubs', `${slug}.json`),
    JSON.stringify(
      {
        id: slug,
        slug,
        name: displayName,
        themePreset: 'classic',
        motionPreset: 'rich',
        domains: [`${slug}.example.com`],
        defaultLocale: 'id',
        supportedLocales: ['id', 'en'],
        seo: {
          title: `${displayName} marketplace`,
          description: `Canonical marketplace preset for ${displayName}.`,
          ogTitle: `${displayName} marketplace`,
          ogDescription: `Canonical marketplace preset for ${displayName}.`,
        },
      },
      null,
      2,
    ),
  ],
]);

for (const [filePath, content] of files) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

console.log(`Scaffolded app shell for ${slug} at ${appDir}`);
console.log(`Manifest stub created at config/platform-stubs/${slug}.json`);
