// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  Home: {
    location: 'Location';
    searchPlaceholder: 'Search {service} or {category}...';
    appointment: 'Appointment';
    popularServices: 'Popular {service}s';
    explore: 'Explore';
    categories: 'Categories';
    professionalsNearYou: '{professional} near you';
    visitorActivityTitle: 'Sign in to view your activity';
    visitorActivityDescription: 'Activity history, chat with providers, payments, and reviews are only available to signed-in customers.';
    visitorActivityPrimaryCta: 'Sign In / Register Customer';
    visitorActivitySecondaryCta: 'Professional Portal';
    professionalActivityTitle: 'You are currently in professional mode';
    professionalActivityDescription: 'Use the professional portal to manage profile readiness, active services, coverage, and operational activity without mixing it with the customer flow.';
    professionalActivityPrimaryCta: 'Open Professional Dashboard';
    professionalActivitySecondaryCta: 'View customer catalog';
  };
  Navigation: {
    home: 'Home';
    search: 'Search';
    experts: 'Experts';
    activity: 'Activity';
  };
  Onboarding: {
    getStarted: 'Get Started';
    heroHint: 'Choose the path that fits best.';
    modeCount: '3 modes';
    accessPrompt: 'Choose the access flow you want to use first.';
    accessBadge: 'Access';
    visitorTitle: 'Continue as visitor';
    visitorDescription: 'Explore services and professionals without signing in.';
    customerTitle: 'Sign in / register customer';
    customerDescription: 'Save activity, bookings, and family follow-up.';
    professionalTitle: 'Sign in as a professional';
    professionalDescription: 'Use a separate professional path so the customer flow stays focused.';
  };
  CustomerAccess: {
    navTitle: 'Customer Access';
    eyebrow: 'Customer Access';
    demoBadge: 'Frontend Demo';
    alreadyCustomer: 'You are already in customer mode. Continue to the page you need.';
    tabs: {
      login: 'Sign In';
      register: 'Register';
    };
    intent: {
      general: {
        title: 'Sign in as a customer to continue';
        description: 'Customer access is used for activity, bookings, family preferences, and care follow-up.';
      };
      activity: {
        title: 'Your activity requires a customer account';
        description: 'Activity history, payments, chat, and reviews only appear after you sign in as a customer.';
      };
      notifications: {
        title: 'Customer notifications are only available for signed-in accounts';
        description: 'Schedule updates, professional replies, payment reminders, and family follow-up only appear for active customer accounts.';
      };
      profile: {
        title: 'Customer profile is separate from visitor mode';
        description: 'Account details, family preferences, and account security are only available for signed-in customers.';
      };
      booking: {
        title: 'Booking is only for signed-in customers';
        description: 'Sign in as a customer so schedules, payments, and care follow-up can be stored properly.';
      };
    };
    benefits: {
      savedHistory: 'Activity and care status stay saved';
      familyContext: 'Chat and family context stay connected';
      followUp: 'Bookings and follow-up feel consistent';
    };
    fields: {
      phone: 'WhatsApp number';
      password: 'Password';
      fullName: 'Full name';
      city: 'Home city';
    };
    placeholders: {
      phone: 'Example: +62 812 3456 7890';
      password: 'Enter a demo password';
      fullName: 'Your name';
      city: 'Example: Depok';
    };
    errors: {
      loginPhoneRequired: 'WhatsApp number is required for the login simulation.';
      loginPasswordRequired: 'Password is required for the login simulation.';
      registerNameRequired: 'Full name is required for the registration simulation.';
      registerPhoneRequired: 'WhatsApp number is required for the registration simulation.';
    };
    actions: {
      login: 'Sign in and continue';
      register: 'Register and continue';
      continueVisitor: 'Continue as visitor';
    };
    registerHelper: 'This form is still a frontend-only simulation. After submitting, the app will switch to customer mode without backend auth.';
    visitorEyebrow: 'Visitor mode';
    visitorDescription: 'Visitors can still explore services and professionals, but activity, booking, and customer profile are gated to this page.';
    professional: {
      eyebrow: 'Professional Portal';
      title: 'Professional access is separated from the customer app';
      description: 'We separate the professional flow so customer navigation stays focused on discovery, booking, and family activity.';
      cta: 'Open professional portal';
    };
  };
  Notifications: {
    title: 'Notifications';
    eyebrow: 'Customer updates';
    heroTitle: 'Track customer updates without losing context';
    heroDescriptionUnread: 'You still have {count, number} notifications to open so schedules, chat, and payments stay in sync.';
    heroDescriptionClear: 'You are all caught up. Keep monitoring appointments and conversations from one place.';
    openAriaLabel: 'Open customer notifications';
    summary: {
      unread: 'Unread';
      total: 'Total updates';
    };
    filters: {
      all: 'All';
      unread: 'Unread';
      appointments: 'Appointments';
      messages: 'Messages';
    };
    sections: {
      today: 'Today';
      earlier: 'Earlier';
    };
    types: {
      appointment: 'Appointment';
      message: 'Message';
      payment: 'Payment';
      account: 'Account';
    };
    badges: {
      unread: 'New';
    };
    actions: {
      markAllRead: 'Mark all read';
      openActivity: 'Open detail';
      replyNow: 'Reply now';
      completePayment: 'Pay now';
      openProfile: 'Open profile';
      leaveReview: 'Leave review';
    };
    empty: {
      title: 'No notifications match this filter';
      description: 'Try switching back to all updates to review the latest schedule, payment, or professional message.';
      resetAction: 'Show all';
    };
  };
  ProfessionalAccess: {
    navTitle: 'Professional Access';
    eyebrow: 'Professional Access';
    demoBadge: 'Frontend Demo';
    title: 'Enter the professional portal';
    alreadyProfessional: 'You are already in professional mode. Open the dashboard to continue.';
    loginHelper: 'Use the demo WhatsApp number and password. If you forget the password, send a reset link to the same number.';
    connectedProfileLabel: 'Connected public profile';
    language: {
      title: 'Language';
      description: 'Keep the professional portal in the language you prefer.';
    };
    tabs: {
      login: 'Sign In';
      register: 'Register';
    };
    profileSelectorLabel: 'Choose a professional demo profile';
    profileSelectorHint: 'This demo profile links the auth flow, dashboard, and public professional profile together.';
    fields: {
      phone: 'WhatsApp number';
      password: 'Password';
      fullName: 'Full name';
      city: 'Home city';
      credential: 'STR / license number';
    };
    placeholders: {
      phone: 'Example: +62 812 3000 0000';
      password: 'Enter a demo password';
      fullName: 'Professional name';
      city: 'Example: South Tangerang';
      credential: 'Example: STR-001-2026';
    };
    errors: {
      loginPhoneRequired: 'WhatsApp number is required for the professional login simulation.';
      loginPasswordRequired: 'Password is required for the professional login simulation.';
      registerNameRequired: 'Full name is required for the professional registration simulation.';
      registerPhoneRequired: 'WhatsApp number is required for the professional registration simulation.';
      registerCredentialRequired: 'STR / license number is required for the professional registration simulation.';
    };
    actions: {
      openDashboard: 'Open dashboard';
      openProfile: 'Professional profile';
      login: 'Sign in to portal';
      register: 'Register and open profile';
      forgotPassword: 'Forgot password';
      sendResetLink: 'Send reset link';
      useAnotherAccount: 'Use another account';
      customer: 'I am a customer';
      visitor: 'Back as visitor';
    };
    forgotPassword: {
      title: 'Reset professional password';
      description: 'This is a frontend simulation. Enter the professional WhatsApp number to receive a password reset link and continue the login flow.';
      phoneLabel: 'WhatsApp number for reset';
      success: 'A demo password reset link was sent to that WhatsApp number.';
      error: 'Enter a WhatsApp number before sending the reset link.';
    };
    registerHelper: 'After registering, you will go straight to the professional profile to start managing the portal. The connected public profile focus is: {category}.';
    fallbackCategory: 'Professional';
    separationTitle: 'Customer and professional paths stay separate';
    separationDescription: 'Customers focus on discovery and booking. Professionals focus on readiness, services, coverage, and operations.';
  };
  ProfessionalPortal: {
    headerLabel: 'Professional area';
    completionLabel: 'Completion';
    metrics: {
      rating: 'Rating';
      response: 'Response';
      averagePrice: 'Average price';
      activeServices: 'Active services';
      coverage: 'Coverage';
      areaUnit: 'areas';
    };
    actions: {
      viewPublicProfile: 'Public profile';
      openCatalog: 'Customer catalog';
    };
    notifications: {
      eyebrow: 'Update center';
      title: 'Professional notifications';
      openAriaLabel: 'Open professional notifications';
      heroDescriptionUnread: 'You still have {count, number} updates to review so inbound requests, operational readiness, and service schedules stay organized.';
      heroDescriptionClear: 'All professional updates are read. Use this screen to keep request-board and operational reminders in one place.';
      summary: {
        unread: 'Unread';
        requests: 'Request updates';
        operations: 'Operational updates';
      };
      filters: {
        all: 'All';
        unread: 'Unread';
        requests: 'Request board';
        operations: 'Operations';
      };
      sections: {
        actionNeeded: 'Action needed';
        monitoring: 'Keep monitoring';
      };
      types: {
        request: 'Request';
        schedule: 'Schedule';
        operations: 'Operations';
      };
      badges: {
        unread: 'New';
        urgent: 'Urgent';
      };
      actions: {
        markAllRead: 'Mark all read';
        openRequestBoard: 'Open request board';
        reviewProfile: 'Continue onboarding';
        reviewServices: 'Review services';
        reviewCoverage: 'Review coverage';
      };
      labels: {
        system: 'System';
      };
      emptyTitle: 'No notifications match this filter';
      emptyDescription: 'Switch back to all updates to review the latest request-board activity and operational reminders.';
      items: {
        newRequestTitle: 'New request from {client}';
        newRequestBody: '{service} for {area} just came in. Review the client need and send an initial response before the queue slips.';
        quotedRequestTitle: 'A quote still needs follow-up';
        quotedRequestBody: "{client}'s {service} case is already in the quoted stage. Recheck pricing, proof, and response expectations before the next follow-up.";
        scheduledRequestTitle: 'A scheduled case needs monitoring';
        scheduledRequestBody: '{client} is already scheduled for {service}. Keep the visit details, reminders, and handoff channel ready.';
        completedRequestTitle: 'Service recap has been saved';
        completedRequestBody: '{service} for {client} is completed. Review the customer summary and internal notes before considering the case fully wrapped.';
        servicesMissingTitle: 'No active services are visible yet';
        servicesMissingBody: 'Activate at least one service so customers can see pricing, duration, and booking flow directly from your public profile.';
        featuredServiceTitle: 'No featured service has been selected';
        featuredServiceBody: 'Choose one featured service so the dashboard summary and public profile have a clear primary offer.';
        acceptingPausedTitle: 'New client intake is currently paused';
        acceptingPausedBody: 'The public profile is still visible, but new requests will not come in. Review the coverage settings if you want to reopen intake.';
        coverageMissingTitle: 'Coverage area is not configured yet';
        coverageMissingBody: 'Add at least one coverage area so home-visit requests and practice location data stay consistent across the portal.';
        reviewPendingTitle: 'Profile submission is waiting for admin review';
        reviewPendingBody: 'Your onboarding checklist is already submitted. Track the review status here while waiting for approval or revision notes.';
        reviewChangesRequestedTitle: 'Admin requested profile revisions';
        reviewChangesRequestedBody: 'Open the onboarding summary, fix the flagged sections, and resubmit the profile so publishing can continue.';
        reviewVerifiedTitle: 'Verification passed and publishing is ready';
        reviewVerifiedBody: 'The admin review is complete. Publish the professional profile when you are ready to go live in the catalog.';
      };
    };
    onboarding: {
      eyebrow: 'Activation';
      adminNote: 'Admin note';
      metrics: {
        progress: 'Onboarding progress';
        blocking: 'Blocking items';
      };
      actions: {
        completeNextStep: 'Complete next step';
        submit: 'Submit to admin';
        resubmit: 'Resubmit to admin';
        simulateRevision: 'Simulate revision';
        simulateVerify: 'Simulate verify';
        publish: 'Publish profile';
      };
      sections: {
        identity: 'Profile';
        coverage: 'Coverage';
        services: 'Services';
        availability: 'Booking Hours';
        portfolio: 'Portfolio';
      };
      sectionProgress: '{completed, number}/{total, number} tasks completed';
      sectionBlocking: '{count, number} blockers';
      sectionDone: 'Ready';
      status: {
        draft: {
          title: 'Profile is still inactive';
          description: 'Complete the required setup so the profile can be submitted for admin review.';
        };
        ready_for_review: {
          title: 'Ready to submit for admin review';
          description: 'All blocking onboarding items are complete. Submit the profile when you are ready.';
        };
        submitted: {
          title: 'Waiting for admin review';
          description: 'The profile is submitted and still hidden from the public catalog until the review finishes.';
        };
        changes_requested: {
          title: 'Revisions are required before publishing';
          description: 'Review the admin note, fix the flagged sections, and submit the profile again.';
        };
        verified: {
          title: 'Verified and ready to publish';
          description: 'Admin approval is complete. Publish the profile when you want to go live.';
        };
        published: {
          title: 'Profile is live';
          description: 'The professional profile is already visible in the public catalog.';
        };
      };
      demoRevisionSuccess: 'Demo review moved the profile to revision requested.';
      demoVerifySuccess: 'Demo review moved the profile to verified.';
      publishSuccess: 'Profile was published to the catalog.';
      submitSuccess: 'Profile was submitted for admin review.';
      validationNotice: 'Complete all blocking onboarding items before submitting to admin.';
    };
    tabs: {
      requests: 'Requests';
      services: 'Services';
      availability: 'Booking Hours';
      portfolio: 'Portfolio';
      coverage: 'Coverage';
      trust: 'Trust';
    };
    units: {
      kilometers: '{count} km';
    };
    requests: {
      summaryDescription: 'New requests open by default so inbound work is easier to triage. Switch stages to review quoted, scheduled, and completed cases with their supporting proof.';
      visibleCount: '{status}: {count, number}';
      statusUpdateTitle: 'Update request stage';
      closeDialogEyebrow: 'Close request';
      closeButton: 'Close editor';
      saveButton: 'Save status update';
      fields: {
        service: 'Service';
        area: 'Area';
        budget: 'Budget';
        note: 'Client note';
        currentStatus: 'Current status';
        customerStatus: 'Customer lifecycle';
        requestedMode: 'Requested mode';
      };
      moveTo: 'Move to stage';
      declineAction: 'Decline request';
      cancelAction: 'Cancel appointment';
      timelineTitle: 'Stage progress';
      updateAction: 'Move to {status}';
      closeDialogDescription: 'Use chat for negotiation only. If the request cannot continue, formally reject it or cancel the appointment from here.';
      closeReasonLabel: 'Reason for closing';
      closeReasonPlaceholder: 'Explain briefly why this request needs to be declined or cancelled.';
      closeOutcomeTitle: 'Customer financial outcome';
      closeStatusPreview: {
        requested: 'The request is still under review, so declining it closes the flow without a refund.';
        approved_waiting_payment: 'Payment has not settled yet, so cancelling should void the unfinished payment.';
        paid: 'The order is already paid, so the customer should receive a full refund.';
        confirmed: 'The order is already confirmed, so the customer should receive a full refund.';
      };
      closeOutcome: {
        none: 'No financial impact';
        void_pending_payment: 'Pending payment voided';
        full_refund: 'Full refund to customer';
        no_refund: 'No refund';
        manual_refund_required: 'Manual refund review';
      };
      closeSave: {
        rejected: 'Decline request';
        cancelled: 'Cancel appointment';
      };
      evidence: {
        title: 'Supporting evidence';
        description: 'Sensitive status updates should include a customer-facing summary and proof so the change can be audited by both sides.';
        helper: 'Add the summary shared to the customer, then attach proof such as a quote, schedule confirmation, invoice, recap, or other supporting link.';
        customerSummaryLabel: 'Customer-facing update summary';
        noteLabel: 'Internal proof note';
        urlLabel: 'Evidence link (optional)';
        customerSummary: 'Customer update';
        internalNote: 'Internal proof note';
        historyEmpty: 'No stage update has been saved yet. This request is still waiting for the first professional response.';
        updatedAt: 'Updated';
        openLink: 'Open evidence';
        empty: 'No supporting evidence has been attached for this status yet.';
      };
      requirements: {
        customerSummary: 'Customer-facing summary required';
        evidence: 'Proof required';
        internalNote: 'Internal note required for completion';
      };
      priority: {
        high: 'High priority';
        medium: 'Medium priority';
        low: 'Low priority';
      };
      status: {
        'new': 'New requests';
        quoted: 'Quoted';
        scheduled: 'Scheduled';
        completed: 'Completed';
      };
      preliveTitle: 'Requests are locked until the profile goes live';
      preliveDescription: 'Finish onboarding, submit the profile to admin, and publish it first. After that, incoming requests will start appearing here.';
      emptyTitle: 'No requests in this stage';
      emptyDescription: 'Switch to another stage or wait for new customer activity to show up here.';
      errors: {
        customerSummaryRequired: 'Write the customer-facing summary before saving this status update.';
        evidenceNoteRequired: 'Add an internal completion note before marking this request as completed.';
        evidenceRequired: 'Add an internal note or an evidence link before saving this status update.';
        invalidTransition: 'This request can only move to the next valid stage.';
        paymentPending: 'The schedule cannot be locked before the customer payment is completed.';
        closeReasonRequired: 'Write a short reason before closing this request.';
      };
      saveSuccess: 'Request for {client} was updated to {status}.';
      closeSuccess: {
        rejected: 'Request for {client} was declined.';
        cancelled: 'Appointment for {client} was cancelled.';
      };
    };
    services: {
      title: 'Services visible to customers';
      description: 'Choose from existing service templates, then complete pricing, duration, modes, and booking flow shown in the customer catalog.';
      activeLabel: 'Active services';
      averagePriceLabel: 'Average price';
      activeCount: 'active services';
      activeBadge: 'Active';
      templateBadge: 'Ready to fill';
      templateLibrary: 'Available service templates';
      editorTitle: 'Configure service details';
      featuredBadge: 'Featured';
      fields: {
        summary: 'Service summary';
        price: 'Displayed price';
        duration: 'Duration';
        bookingFlow: 'Booking flow';
        serviceModes: 'Service modes';
        defaultMode: 'Default mode';
        featured: 'Set as featured service';
      };
      featuredHint: 'The featured service is prioritized in the public profile and dashboard summary.';
      availabilityNoteEyebrow: 'Shared booking hours';
      availabilityNoteTitle: 'Booking days and times are managed once from the Booking Hours tab.';
      availabilityNoteDescription: 'All offline services read the same professional-wide availability so operations stay cleaner and do not branch per service.';
      editButton: 'Edit service';
      closeButton: 'Close editor';
      saveButton: 'Save service details';
      archiveButton: 'Hide from catalog';
      activateButton: 'Add from template';
      activateSuccess: '{service} was added from the template library.';
      archiveSuccess: '{service} was hidden from the public catalog.';
      saveSuccess: 'Service details for {service} were saved.';
    };
    availability: {
      title: 'Shared booking hours';
      heroTitle: 'Weekly hours for every offline service';
      heroDescription: 'Set regular working days once, then add special-date adjustments only when needed. Customers will still see bookable dates and times generated from these shared rules.';
      metrics: {
        activeServices: 'Active services';
        activeModes: 'Offline modes';
        days: 'Weekly open days';
        notice: 'Booking notice';
      };
      modeSectionTitle: 'Working hours by offline mode';
      modeSectionDescription: 'Split home-visit and onsite hours only when each mode really needs a different routine, including its latest booking notice.';
      modeSummaryValue: '{days, number} weekly days • {slots, number} special adjustments';
      modeSummaryEmpty: 'This mode does not have weekly hours yet.';
      readyBadge: 'Ready';
      emptyBadge: 'Empty';
      noticeFallback: 'Not set';
      summaryWeekdays: 'Weekly days';
      summaryWeekdaysHint: 'Regular open days for this mode.';
      summaryOverrides: 'Special dates';
      summaryOverridesHint: 'Holiday or custom-hour adjustments.';
      minimumNoticeTitle: 'Latest booking notice';
      minimumNoticeHint: 'The latest time a customer may still book before the session starts.';
      minimumNoticeDescription: 'Use this to block bookings that are too close to the service time. Customer date and time choices will be filtered automatically from this rule.';
      minimumNoticeActiveHint: 'Currently active for this mode.';
      minimumNoticeInactiveHint: 'Use this as the latest booking notice.';
      noticeValue: '{value, plural, =24 {H-1} =48 {H-2} other {{value, number} hr}}';
      noSpecialDays: 'None yet';
      weeklyHoursTitle: 'Regular working hours';
      weeklyHoursDescription: 'This is the base schedule customers will see most of the time. Turn on only the days that really accept bookings.';
      weeklyHoursToggleDescription: 'When turned on, the app will automatically generate customer booking times from these hours.';
      startTimeLabel: 'Start time';
      endTimeLabel: 'End time';
      specialDatesTitle: 'Special-day adjustments';
      specialDatesDescription: 'Use this only for holidays, shorter days, or custom hours that should temporarily override the weekly routine.';
      addOverride: 'Add special day';
      specialDateCardTitle: 'Special date';
      specialDateCardDescription: 'Choose whether this day is closed or follows a custom schedule.';
      specialDateLabel: 'Date';
      specialDateClosed: 'Closed';
      specialDateCustomHours: 'Custom hours';
      specialDateNoteLabel: 'Internal note';
      specialDatesEmptyTitle: 'There are no special-date adjustments yet.';
      specialDatesEmptyDescription: 'Leave this empty if the regular weekly hours are already enough.';
      specialDayCount: '{count, number} special days';
      weekdays: {
        monday: 'Monday';
        tuesday: 'Tuesday';
        wednesday: 'Wednesday';
        thursday: 'Thursday';
        friday: 'Friday';
        saturday: 'Saturday';
        sunday: 'Sunday';
      };
      editButton: 'Edit booking hours';
      editorTitle: 'Manage booking hours';
      editorHeroTitle: 'Professional working hours';
      editorDescription: 'Changes here apply to every offline service that supports the selected mode. Customers will receive generated booking times from these rules.';
      closeButton: 'Close editor';
      saveButton: 'Save booking hours';
      saveSuccess: 'Shared booking hours were updated.';
    };
    portfolio: {
      title: 'Portfolio and proof of work';
      description: 'Curate case studies, outcomes, and visual assets so customers can understand the quality and context behind your work.';
      publicCountLabel: 'Public portfolio';
      galleryCountLabel: 'Gallery assets';
      addButton: 'Add portfolio';
      editButton: 'Edit portfolio';
      galleryEditButton: 'Edit asset';
      closeButton: 'Close editor';
      editorTitle: 'Portfolio editor';
      fields: {
        title: 'Case study title';
        period: 'Period';
        service: 'Linked service';
        summary: 'Case summary';
        outcomes: 'Key outcomes';
        image: 'Image URL';
        visibility: 'Visibility';
      };
      noServiceOption: 'No specific service';
      visibility: {
        public: 'Public';
        private: 'Private';
      };
      saveButton: 'Save portfolio';
      deleteButton: 'Delete portfolio';
      galleryTitle: 'Profile gallery';
      galleryDescription: 'Add assets that strengthen customer trust in your practice, services, and outcomes.';
      galleryAddButton: 'Add asset';
      galleryFields: {
        label: 'Asset label';
        alt: 'Alt text';
        image: 'Image URL';
        featured: 'Set as featured asset';
      };
      galleryFeaturedHint: 'The featured asset will appear first in the public gallery.';
      gallerySaveButton: 'Save asset';
      galleryDeleteButton: 'Delete asset';
      featuredAsset: 'Featured asset';
      addSuccess: 'A new portfolio draft was added.';
      deleteSuccess: 'Portfolio was removed from the simulation.';
      galleryAddSuccess: 'A new gallery asset was added.';
      galleryDeleteSuccess: 'Gallery asset was removed from the simulation.';
      gallerySaveSuccess: 'Gallery asset was updated.';
      saveSuccess: 'Portfolio was updated.';
    };
    coverage: {
      title: 'Service coverage';
      city: 'Home city';
      scopeTitle: 'Active service footprint';
      scopeDescription: 'Keep the active areas and service reach tidy so incoming demand matches your real operations.';
      operationsTitle: 'Operational status';
      operationsDescription: 'Monitor new-client intake and the coverage center from one place.';
      coordinates: 'Coverage center coordinates';
      areaCountLabel: 'Active areas';
      modeCoverageLabel: 'Enabled service modes';
      emptyPracticeAddress: 'The practice address is not filled in yet.';
      emptyPublicBio: 'A public bio has not been added yet.';
      emptyAreaSelection: 'There are no active areas yet. Add coverage areas so the profile is ready to receive matching requests.';
      emptyModeSelection: 'No active service modes are ready yet. Enable at least one active service in Services.';
      fields: {
        city: 'Primary city / regency';
        responseTime: 'Response time target';
        practiceLabel: 'Practice location label';
        practiceAddress: 'Practice address';
        publicBio: 'Public bio';
        radius: 'Home-visit radius (km)';
        latitude: 'Coverage center latitude';
        longitude: 'Coverage center longitude';
        areaSelection: 'Select coverage areas';
      };
      switches: {
        accepting: 'Accepting new clients';
        acceptingDescription: 'Turn this off if the profile should stay visible but stop taking new requests.';
        instant: 'Auto-approve instant bookings';
        instantDescription: 'Enable this if instant bookings can go through without manual review.';
        onLabel: 'On';
        offLabel: 'Off';
      };
      editButton: 'Edit coverage';
      closeButton: 'Close editor';
      saveButton: 'Save coverage settings';
      saveSuccess: 'Coverage and operational settings were updated.';
      validationMessage: 'Choose at least one coverage area before saving. Service modes are managed in Services and working hours are managed in Booking Hours.';
    };
    trust: {
      credentials: 'Credentials and compliance';
      credentialsDescription: 'Add licenses, certifications, and training proof that customers should see on your public profile.';
      feedback: 'Feedback and service quality';
      feedbackDescription: 'Customer-generated quality signals from reviews and completed appointments. These are not editable from the dashboard.';
      testimonials: 'Recent customer voices';
      testimonialsDescription: 'Customer quotes stay read-only so the public trust layer remains auditable.';
      stories: 'Practice stories and proof';
      storiesDescription: 'Curate a few real moments from your practice so customers understand how you work before they book.';
      customerSignals: 'Customer trust signals';
      customerGeneratedBadge: 'Customer generated';
      addCredentialButton: 'Add credential';
      addStoryButton: 'Add story';
      closeButton: 'Close editor';
      saveButton: 'Save trust entry';
      deleteButton: 'Delete trust entry';
      emptyCredentialsTitle: 'No credentials have been added yet.';
      emptyCredentialsDescription: 'Start with the license, training, or certification that matters most for new customers.';
      emptyStoriesTitle: 'No practice stories are visible yet.';
      emptyStoriesDescription: 'Add one concise story so customers can see how your service is delivered in real situations.';
      credentialEditor: {
        title: 'Credential entry';
        fields: {
          title: 'Credential title';
          issuer: 'Issuer';
          year: 'Year';
          note: 'What customers should know';
        };
      };
      storyEditor: {
        title: 'Practice story';
        fields: {
          title: 'Story title';
          capturedAt: 'Captured at';
          location: 'Location label';
          image: 'Image URL';
          note: 'Story summary';
        };
      };
      summary: {
        recommendationRate: 'Recommendation rate';
        repeatClientRate: 'Repeat clients';
      };
      signals: {
        services: 'Bookable services';
        portfolio: 'Public portfolio';
        gallery: 'Visual assets';
        response: 'Response target';
      };
      credentialDeleteSuccess: 'Credential removed.';
      credentialSaveSuccess: 'Credential updated.';
      storyDeleteSuccess: 'Practice story removed.';
      storySaveSuccess: 'Practice story updated.';
    };
  };
  ProfessionalProfile: {
    navTitle: 'Professional Profile';
    buttons: {
      close: 'Close';
      editProfile: 'Edit';
    };
    quickActions: {
      dashboardTitle: 'Dashboard';
      dashboardDescription: 'Open requests, readiness, and the main professional summary.';
      publicProfileTitle: 'Public profile';
      publicProfileDescription: 'Preview the page customers will see before they book.';
    };
    language: {
      title: 'App language';
      compactDescription: 'Use the language that feels easiest';
    };
    actions: {
      logout: 'Exit professional mode';
    };
    menu: {
      accountDescription: 'Identity, contact number, public bio, and response target.';
      securityDescription: 'Change the password or send a reset link when access is blocked.';
      supportDescription: 'Disputes, refunds, reporting, and dashboard issues through admin.';
    };
    account: {
      title: 'Professional account details';
      description: 'Keep identity details, the public bio, and the response target clear so customers understand the profile quickly.';
      saveButton: 'Save profile changes';
      success: 'The professional profile was updated.';
      profileCompletionHint: 'The more complete this profile is, the more ready the public profile and operations dashboard become.';
      fields: {
        displayName: 'Professional name';
        phone: 'WhatsApp number';
        city: 'Home city';
        credentialNumber: 'License number';
        responseTimeGoal: 'Response time target';
        profileCompletion: 'Profile completion';
        publicBio: 'Public bio';
      };
      errors: {
        displayNameRequired: 'Professional name is required.';
        phoneRequired: 'WhatsApp number is required.';
        credentialRequired: 'License number is required.';
      };
    };
    security: {
      title: 'Account security';
      description: 'Manage the professional demo password and keep a reset path ready whenever the password is forgotten.';
      saveButton: 'Save new password';
      success: 'The demo professional password was updated.';
      resetTitle: 'Forgot password?';
      resetDescription: 'Send a reset link to the professional WhatsApp number so access can be restored without changing profile data.';
      resetButton: 'Send password reset';
      resetSuccess: 'The demo password reset link was sent.';
      fields: {
        currentPassword: 'Current password';
        newPassword: 'New password';
        confirmPassword: 'Confirm new password';
        resetPhone: 'WhatsApp number for reset';
      };
      rules: {
        minLength: 'At least 8 characters';
        hasUppercase: 'Contains 1 uppercase letter';
        hasNumber: 'Contains 1 number';
        matches: 'Password confirmation must match';
      };
      status: {
        ready: 'Ready';
        pending: 'Pending';
      };
      errors: {
        currentRequired: 'Enter the current password first.';
        newPasswordWeak: 'The new password does not meet the minimum security rules.';
        confirmMismatch: 'The password confirmation does not match the new password.';
        resetPhoneRequired: 'Enter the WhatsApp number for the reset flow first.';
      };
    };
    support: {
      title: 'Admin support';
      description: 'Send disputes, refunds, reports, or dashboard issues without leaving the professional profile.';
      submitButton: 'Send ticket to admin';
      success: 'Ticket {ticketId} was created and is now in the admin queue.';
      entry: {
        title: 'Need to escalate to admin?';
        description: 'Use one lane for booking disputes, refunds, customer reports, or operational bugs.';
        action: 'Open support hub';
        responseBadge: '<10 min triage';
        issueBadge: 'Dispute';
        refundBadge: 'Refund';
        reportBadge: 'Report';
      };
      overview: {
        title: 'When admin should step in';
        description: 'Use this area when booking disputes, payment corrections, safety risks, or technical blockers can no longer be resolved from the normal dashboard flow.';
      };
      metrics: {
        firstResponse: {
          label: 'First response';
          value: '<10 min';
        };
        reviewWindow: {
          label: 'Evidence review';
          value: '<2 hours';
        };
        resolution: {
          label: 'Resolution target';
          value: '<24 hours';
        };
      };
      moments: {
        caseOne: {
          title: 'Need admin mediation in the booking flow';
          description: 'Use this when schedule disputes, unilateral cancellations, or request states need an admin decision.';
        };
        caseTwo: {
          title: 'Refund or payment correction needs clarification';
          description: 'Choose the refund category so admin can compare payment proof, service status, and cancellation rules.';
        };
        caseThree: {
          title: 'Need to report an account risk or bug';
          description: 'Use this lane for risky customer behavior, suspicious account details, or dashboard bugs that block operations.';
        };
      };
      form: {
        title: 'Create a support ticket';
        description: 'Pick the closest category, choose the follow-up channel, and describe the blocker or dispute so triage starts quickly.';
        categoryLabel: 'Issue category';
        summaryLabel: 'Short summary';
        summaryPlaceholder: 'Example: Refund clarification after a confirmed booking';
        referenceLabel: 'Request or reference code (optional)';
        referencePlaceholder: 'Example: REQ-1024 or invoice';
        channelLabel: 'Preferred follow-up channel';
        contactLabel: 'Contact for follow-up';
        contactPlaceholder: 'WhatsApp number, phone number, or email';
        urgencyLabel: 'Handling priority';
        detailsLabel: 'Issue details';
        detailsPlaceholder: 'Explain the timeline, the current operational state, and the decision you need from admin.';
        helper: 'Tip: include booking timeline, payment status, schedule changes, and any relevant chat evidence. File upload is not available yet, so mention the evidence you already keep.';
      };
      categories: {
        serviceDispute: {
          title: 'Operational dispute';
          description: 'Schedule, cancellation, completion, or order conflict that needs admin mediation.';
        };
        refundClarification: {
          title: 'Refund clarification';
          description: 'Need an admin decision before refund, fee deduction, or payment correction can proceed.';
        };
        accountAccess: {
          title: 'Account access';
          description: 'Cannot sign in, need reverification, or password reset did not restore access.';
        };
        reportCustomer: {
          title: 'Report customer';
          description: 'Safety risk, abusive behavior, or customer data that needs admin review.';
        };
        technicalIssue: {
          title: 'Technical bug';
          description: 'Issue in the dashboard, notifications, request board, or professional profile page.';
        };
        other: {
          title: 'Other issue';
          description: 'Use this when the blocker does not fit the categories above.';
        };
      };
      channels: {
        whatsapp: 'WhatsApp';
        call: 'Phone';
        email: 'Email';
      };
      urgency: {
        normal: {
          title: 'Normal';
          description: 'The issue needs attention, but operations can still continue temporarily.';
        };
        high: {
          title: 'High';
          description: 'The issue is already affecting schedule, payment, or customer response.';
        };
        urgent: {
          title: 'Urgent';
          description: 'Use only when there is a safety risk, active service disruption, or a total technical blocker.';
        };
      };
      flow: {
        title: 'How admin handles it';
        description: 'Every ticket follows the same path so disputes, refunds, and operational reports stay transparent.';
        stepOne: {
          badge: 'Step 1';
          title: 'Ticket logged';
          description: 'Admin receives the category, request reference, follow-up channel, and initial operational context.';
        };
        stepTwo: {
          badge: 'Step 2';
          title: 'Triage and owner assignment';
          description: 'Priority is checked, booking data is pulled, and the ticket is routed to the right admin owner.';
        };
        stepThree: {
          badge: 'Step 3';
          title: 'Evidence review';
          description: 'Admin compares booking logs, payment state, chat timeline, and related reports.';
        };
        stepFour: {
          badge: 'Step 4';
          title: 'Decision and next action';
          description: 'The professional receives the admin decision, next action, and refund/correction status when relevant.';
        };
      };
      recent: {
        title: 'Recent tickets';
        description: 'This section helps professionals track whether admin is still triaging, reviewing, or has already closed the latest case.';
        empty: 'No support ticket yet.';
        ticketLabel: 'Ticket';
        etaLabel: 'Next update target';
        statuses: {
          'new': 'New';
          triaged: 'Triaged';
          reviewing: 'Reviewing';
          resolved: 'Resolved';
          refunded: 'Refund processed';
        };
        etas: {
          normal: '<24 hours';
          high: '<4 hours';
          urgent: '<30 minutes';
        };
      };
      errors: {
        categoryRequired: 'Choose the issue category first.';
        contactRequired: 'Enter a contact that admin can use for follow-up.';
        detailsRequired: 'Describe the issue so admin can continue the investigation.';
      };
    };
  };
  Professional: {
    about: 'About {professional}';
    available: 'Available';
    unavailable: 'Unavailable';
    coverageArea: 'Coverage area';
    coverageIn: 'In coverage';
    coverageOut: 'Out of coverage';
    coordinates: 'Coordinates';
    distance: 'Distance';
    time: 'Time';
    homeVisitRadius: 'Home care radius';
    modeHomeVisit: 'Home care';
    modeOnline: 'Online';
    modeOnsite: 'Visit provider';
    onlineOnlyCoverage: 'No home care';
    paginationNext: 'Next';
    paginationPrevious: 'Previous';
    paginationStatus: 'Page {current, number} of {total, number}';
    practiceLocation: 'Service point';
    rating: 'Rating';
    selectedArea: 'User area';
    selectedSchedule: 'Selected schedule';
    selectedServiceLabel: 'Active service';
    selectionResumeEyebrow: 'Booking summary';
    selectionResumeEmptyTitle: 'Start by choosing a service';
    selectionResumeIncompleteTitle: 'Complete the booking choice';
    selectionResumeReadyTitle: 'Choice ready to request';
    selectionResumeEmptyDescription: 'Tap one service from the list to open the dialog and start configuring your booking choice.';
    selectionResumeModeDescription: 'The service is already chosen. Continue by selecting the mode that fits best.';
    selectionResumeScheduleDescription: 'The mode is already chosen. Pick the visit day and time so the booking is ready to request.';
    selectionResumeReadyDescription: 'The booking summary is complete. Review the details once more and continue with the booking button below.';
    selectionProgressBadge: 'Complete choice';
    selectionReadyBadge: 'Ready to request';
    serviceSectionHelper: 'Choose one service first, then configure its mode and schedule in the dialog. After that you can continue with the booking button below.';
    selectionStepChoose: 'Choose the most relevant service';
    selectionStepConfigure: 'Set the mode and schedule if needed';
    selectionStepBook: 'Request booking once the choice is ready';
    selectionEmptyTitle: 'Choose one service to start booking';
    selectionEmptyDescription: 'The list below shows every service this professional offers. Tap one service to open its details and configure the booking.';
    selectServiceAction: 'Choose service';
    changeServiceAction: 'Edit choice';
    configureSelectionAction: 'Configure';
    selectedModeLabel: 'Selected mode';
    selectedPriceLabel: 'Service price';
    selectionModePending: 'Choose a service mode first';
    selectionSchedulePending: 'Choose a visit schedule first';
    selectionScheduleNotNeeded: 'No extra schedule needed';
    serviceDialogTitle: 'Configure service choice';
    serviceDialogDescription: 'Choose an available mode, then set the schedule if this service requires a visit.';
    closeServiceDialog: 'Close service dialog';
    serviceHighlightsTitle: 'What you will get';
    saveServiceSelection: 'Use this selection';
    serviceModes: 'Service modes';
    serviceSearchPlaceholder: 'Search services, summaries, or tags...';
    serviceResultsCount: '{count, number} matching services';
    serviceListTitle: 'All services from this professional';
    serviceSelected: 'Selected';
    allCategories: 'All categories';
    allModes: 'All modes';
    categoryFilterLabel: 'Category';
    modeFilterLabel: 'Mode';
    resetServiceFilters: 'Reset filters';
    bookingFlowLabel: 'Flow';
    bookingFlowInstant: 'Instant';
    bookingFlowRequest: 'Request';
    chooseServiceMode: 'Choose service mode';
    chooseVisitDay: 'Choose visit day';
    chooseVisitTime: 'Choose visit time';
    minimumNoticeInline: 'Bookings for this mode close {value} before the schedule starts.';
    scheduleRequired: 'Choose a visit time before continuing with an offline booking.';
    offlineScheduleRequired: 'Choose a visit day and time before continuing the offline booking.';
    modeReadyToBook: 'Ready to book';
    modeNotBookable: 'Not bookable now';
    slotOpenLabel: 'open';
    slotAvailable: 'Available';
    slotLimited: 'Limited';
    slotBooked: 'Booked';
    noFilteredServices: 'No services match the current filters.';
    noFilteredServicesHint: 'Try another search term or reset the filters to see more services.';
    makeAppointment: 'Request booking';
    experience: 'Years Exp.';
    requestUpdates: {
      eyebrow: 'Request update';
      title: 'Your latest request with {professional}';
      description: 'This status is shared by the provider so you can track quotes, scheduling, and completion more transparently.';
      service: 'Service';
      area: 'Area';
      requestedAt: 'Requested';
      updatedAt: 'Last updated';
      submittedSummary: 'Your request has been sent and is waiting for provider review.';
      emptySummary: 'The provider has not added a customer-facing summary for this stage yet.';
      openEvidence: 'Open proof';
    };
    selectionStatusCurrent: 'Next';
    selectionStatusDone: 'Done';
    selectionStatusPending: 'Waiting';
  };
  Explore: {
    title: '{professional}s';
    yourLocation: 'Your Location';
    changeLocation: 'Change location';
    searchPlaceholder: 'Find {professional} by name or city...';
    allExperts: 'All Experts';
    allCategories: 'All Categories';
    topRated: 'Top Rated';
    availableToday: 'Available Today';
    myFavorites: 'My Favorites';
    resultsFound: '{count, number} {count, plural, =1 {Result} other {Results}} Found';
    noResults: 'No results found';
    tryAdjusting: 'Try adjusting your filters or search term.';
    filterTitle: 'Filter {professional}s';
    locationSection: 'Point-Based Location';
    locationPointOnly: 'Point based';
    locationPointHint: 'Enter coordinates or use your current location. The nearest area will be derived from this coordinate point.';
    useCurrentLocation: 'Use My Current Location';
    latitude: 'Latitude';
    longitude: 'Longitude';
    nearestArea: 'Nearest area';
    city: 'City / Regency';
    district: 'District';
    province: 'Province';
    postalCode: 'Postal Code';
    country: 'Country';
    formattedAddress: 'Formatted address';
    invalidCoordinates: 'Invalid coordinates. Use latitude -90..90 and longitude -180..180.';
    locationBrowserUnsupported: 'This browser does not support location detection.';
    locationPermissionDenied: 'Location permission was denied. Enable it in your browser.';
    locationUnavailable: 'Location is currently unavailable from this device.';
    locationTimeout: 'Location detection timed out.';
    locationFetchFailed: 'Failed to detect the current location.';
    locationResolveFailed: 'Failed to map coordinates to mock location details.';
    locationDummyHint: 'Location detail is currently mocked in the frontend. It can be replaced by a reverse geocoding API later without changing the UI.';
    categorySection: 'Category';
    availabilitySection: 'Availability';
    genderPreference: 'Gender Preference';
    favoritesSection: 'My Preferences';
    reset: 'Reset';
    applyFilters: 'Apply Filters';
    resolvingLocation: 'Resolving location...';
  };
  Appointments: {
    title: 'Activity';
    searchPlaceholder: 'Search appointments...';
    active: 'Active';
    history: 'History';
    allStatuses: 'All Statuses';
    noAppointments: 'No active appointments';
    trySearching: 'Try searching or book a new service.';
    status: {
      requested: 'Waiting for Approval';
      approved_waiting_payment: 'Waiting for Payment';
      paid: 'Paid';
      confirmed: 'Confirmed';
      in_service: 'In Service';
      completed: 'Completed';
      cancelled: 'Cancelled';
      rejected: 'Rejected';
      expired: 'Expired';
    };
  };
  Services: {
    globalTitle: 'Global {service}s';
    searchPlaceholder: 'Search {service}...';
    allServices: 'All Services';
    catalogTitle: '{count, number} {count, plural, =1 {Service} other {Services}} Catalog';
    noServices: 'No services found';
    trySearchTerm: 'Try another search term.';
  };
  ServiceDetail: {
    about: 'About this {service}';
    available: 'Available {professional}s';
    expertsCount: '{count, number} {count, plural, =1 {Expert} other {Experts}}';
    noProfessionals: 'No professionals currently provide this service.';
    makeAppointment: 'Request booking';
  };
  UI: {
    seeAll: 'See All';
  };
  Profile: {
    title: 'Profile';
    language: 'Language';
    account: 'Account Details';
    security: 'Account Security';
    logout: 'Log Out';
    buttons: {
      close: 'Close';
      editProfile: 'Edit';
    };
    quickActions: {
      activityTitle: 'Activity';
      activityDescription: 'Review active sessions, progress, and family follow-up.';
      exploreTitle: 'Find care';
      exploreDescription: 'Discover professionals and follow-up services that fit home needs.';
    };
    professionalCard: {
      title: 'Professional Portal Stays Separate';
      description: 'If you are a professional, use this CTA to reach a dedicated area so the customer flow does not get mixed.';
    };
    menu: {
      languageDescription: 'Switch between Bahasa Indonesia and English anytime.';
      accountDescription: 'Primary contact, care focus, and family support.';
      securityDescription: 'New password and account privacy controls.';
      supportDescription: 'Complaints, refunds, reporting, and account issues through admin.';
    };
    accountSheet: {
      title: 'Account Details';
      description: 'Complete your identity, care focus, and family contact so follow-up stays aligned.';
      identityTitle: 'Primary info';
      nameLabel: 'Full name';
      phoneLabel: 'WhatsApp number';
      focusLabel: 'Care focus';
      focusPlaceholder: 'Example: home care, family education, routine follow-up';
      supportTitle: 'Family support contact';
      supportDescription: 'Add the one contact who is most relevant when care coordination is needed.';
      supportNameLabel: 'Support contact name';
      supportRelationLabel: 'Relationship';
      supportPhoneLabel: 'Support contact number';
      supportPlaceholder: 'Partner / parent / caregiver';
      save: 'Save details';
      success: 'Profile details updated successfully.';
      errors: {
        nameRequired: 'Full name is required.';
        phoneRequired: 'WhatsApp number is required.';
        supportContactIncomplete: 'Complete the family support name, relationship, and phone number.';
      };
    };
    securitySheet: {
      title: 'Change Password';
      description: 'Account security matters to keep family data and care history private.';
      currentPasswordLabel: 'Current password';
      newPasswordLabel: 'New password';
      confirmPasswordLabel: 'Confirm new password';
      helperTitle: 'Security checklist';
      helperDescription: 'Use a password that you can remember while still keeping access protected.';
      ruleMinLength: 'At least 8 characters';
      ruleUppercase: 'Includes 1 uppercase letter';
      ruleNumber: 'Includes 1 number';
      ruleMatch: 'Confirmation matches';
      save: 'Update password';
      success: 'Password updated successfully.';
      errors: {
        currentRequired: 'Enter your current password first.';
        newPasswordWeak: 'The new password does not meet the security rules.';
        confirmMismatch: 'The password confirmation does not match.';
      };
    };
    support: {
      title: 'Admin support';
      description: 'Send complaints, refunds, reports, or account issues without leaving the profile page.';
      submitButton: 'Send ticket to admin';
      success: 'Your report was submitted. Ticket {ticketId} is now in the admin queue.';
      entry: {
        title: 'Need admin help?';
        description: 'Use one support lane for complaints, refunds, reporting, or booking issues.';
        action: 'Open support form';
        responseBadge: '<10 min triage';
        issueBadge: 'Complaint';
        refundBadge: 'Refund';
        reportBadge: 'Report';
      };
      overview: {
        title: 'When admin should step in';
        description: 'Use this lane when the provider flow, payment flow, or safety/reporting flow can no longer be resolved from the regular chat.';
      };
      metrics: {
        firstResponse: {
          label: 'First response';
          value: '<10 min';
        };
        reviewWindow: {
          label: 'Evidence review';
          value: '<2 hours';
        };
        resolution: {
          label: 'Resolution target';
          value: '<24 hours';
        };
      };
      moments: {
        caseOne: {
          title: 'Complaint or follow-up is stuck';
          description: 'Use this when service quality, schedule changes, or provider communication already blocks care continuity.';
        };
        caseTwo: {
          title: 'Need a refund or payment correction';
          description: 'Choose the refund/payment category so admin can review payment proof and booking status in one flow.';
        };
        caseThree: {
          title: 'Need to report a profile or behavior';
          description: 'Use reporting for safety concerns, inappropriate conduct, invalid profile details, or repeated unexplained cancellations.';
        };
      };
      form: {
        title: 'Create a support ticket';
        description: 'Pick the closest category, tell us how to reach you, and summarize the issue so triage can start quickly.';
        categoryLabel: 'Issue category';
        summaryLabel: 'Short summary';
        summaryPlaceholder: 'Example: Refund for a cancelled home visit';
        referenceLabel: 'Booking or reference code (optional)';
        referencePlaceholder: 'Example: ACT-2048 or invoice number';
        channelLabel: 'Preferred follow-up channel';
        contactLabel: 'Contact for follow-up';
        contactPlaceholder: 'WhatsApp number, phone number, or email';
        urgencyLabel: 'Handling priority';
        detailsLabel: 'Issue details';
        detailsPlaceholder: 'Explain what happened, when it happened, and what result you expect from admin.';
        helper: 'Tip: include timeline, payment proof reference, schedule changes, and who was involved. File upload is not available yet, so mention the evidence you already have.';
      };
      categories: {
        serviceComplaint: {
          title: 'Service complaint';
          description: 'Quality, attitude, delay, or operational issue during the session.';
        };
        refundRequest: {
          title: 'Refund request';
          description: 'Cancellation, duplicate payment, or service not delivered as agreed.';
        };
        paymentIssue: {
          title: 'Payment issue';
          description: 'Payment failed, charged twice, or billing amount is incorrect.';
        };
        reportProfessional: {
          title: 'Report provider';
          description: 'Profile, conduct, or safety concern involving a provider.';
        };
        accountAccess: {
          title: 'Account access';
          description: 'Cannot log in, reset password fails, or profile access is blocked.';
        };
        other: {
          title: 'Other issue';
          description: 'Use this when the issue does not fit the categories above.';
        };
      };
      channels: {
        whatsapp: 'WhatsApp';
        call: 'Phone';
        email: 'Email';
      };
      urgency: {
        normal: {
          title: 'Normal';
          description: 'The issue matters, but it is not blocking care right now.';
        };
        high: {
          title: 'High';
          description: 'The issue is already affecting schedule, payment, or care continuity.';
        };
        urgent: {
          title: 'Urgent';
          description: 'Use only when there is a safety risk or the active service is disrupted right now.';
        };
      };
      flow: {
        title: 'How admin handles it';
        description: 'Every ticket follows the same path so complaints, refunds, and reports stay traceable.';
        stepOne: {
          badge: 'Step 1';
          title: 'Ticket logged';
          description: 'Your report is recorded with category, follow-up channel, and initial context.';
        };
        stepTwo: {
          badge: 'Step 2';
          title: 'Triage and owner assignment';
          description: 'Admin reviews urgency, checks the booking context, and assigns the right owner.';
        };
        stepThree: {
          badge: 'Step 3';
          title: 'Evidence review';
          description: 'Timeline, payment status, chat context, and report details are reviewed before action is decided.';
        };
        stepFour: {
          badge: 'Step 4';
          title: 'Resolution or refund update';
          description: 'You receive the decision, next action, and refund or correction status.';
        };
      };
      recent: {
        title: 'Recent tickets';
        description: 'This area shows the latest support tickets so customers can tell whether admin is still triaging, reviewing, or has already resolved the issue.';
        empty: 'No support ticket yet.';
        ticketLabel: 'Ticket';
        etaLabel: 'Next update target';
        statuses: {
          'new': 'New';
          triaged: 'Triaged';
          reviewing: 'Reviewing';
          resolved: 'Resolved';
          refunded: 'Refund processed';
        };
        etas: {
          normal: '<24 hours';
          high: '<4 hours';
          urgent: '<30 minutes';
        };
      };
      errors: {
        categoryRequired: 'Choose the issue category first.';
        contactRequired: 'Enter a contact that admin can use for follow-up.';
        detailsRequired: 'Describe the issue so admin can continue the investigation.';
      };
    };
    modeLabels: {
      online: 'Online';
      home_visit: 'Home care';
      onsite: 'Visit provider';
    };
  };
  UiText: {
    terms: {
      professional: 'Professional';
      category: 'Category';
      service: 'Service';
      location: 'Clinic / Private Practice';
      experience: 'Years of Practice';
      patients: 'Patients Served';
    };
    booking: {
      online: 'Online booking created. Continue to scheduling and payment.';
      homeVisit: 'Home care request submitted. The system will check coverage and confirm the schedule.';
      onsite: 'Visit reservation created. Choose an available appointment slot.';
      providerSelectedNotice: '{bookingMessage} Selected professional: {providerName}.';
      serviceSelectedNotice: '{bookingMessage} Selected service: {serviceName}.{scheduleMessage}';
      scheduleNotice: ' Schedule: {dateIso} • {timeLabel}.';
    };
    alerts: {
      chatAutoReply: 'Okay, I received your message.';
      paymentSuccess: 'Payment simulation successful';
      chatSent: 'Message sent in demo mode';
      chatUnavailable: 'Chat is only available for active activities.';
      appointmentCancelled: {
        none: 'Appointment cancelled.';
        void_pending_payment: 'Appointment cancelled. Pending payment was voided.';
        full_refund: 'Appointment cancelled. Customer receives a full refund.';
        no_refund: 'Appointment cancelled. The order passed the refund cutoff.';
        manual_refund_required: 'Appointment cancelled. Refund will be reviewed manually.';
      };
      reviewPhotoReady: 'Review photo ready to upload: {fileName}';
      reviewSuccessWithPhoto: '{successMessage} Photo: {fileName}.';
    };
    appointment: {
      detailTitle: 'Activity Details';
      notFoundMessage: 'Activity not found.';
      backLabel: 'Back';
      welcomeTemplate: 'Hello, how can I help you with your {serviceName} reservation?';
      chatDayLabel: 'TODAY';
      chatInputPlaceholder: 'Write a message...';
      fieldLabels: {
        duration: 'Ordered Duration';
        mode: 'Service Mode';
        note: 'Order Note';
        requestedAt: 'Ordered At';
        status: 'Status';
        time: 'Schedule';
        location: 'Location';
        service: 'Service';
        totalPayment: 'Total Payment';
      };
      actionLabels: {
        detail: 'Details';
        cancel: 'Cancel';
        payNow: 'Pay Now';
        bookAgain: 'Book Again';
      };
      cancellation: {
        title: 'Cancel appointment';
        description: 'Use chat to discuss changes first. If you still need a different time or service, cancel this order and place a new one.';
        submitLabel: 'Confirm cancellation';
        keepLabel: 'Keep appointment';
        reasonLabel: 'Reason for cancellation';
        reasonPlaceholder: 'Explain briefly why you need to cancel this order.';
        policyTitle: 'Cancellation policy';
        outcomeTitle: 'Financial outcome';
        customerNoPaymentPolicy: 'Before payment settles, cancellation closes the order without a refund flow.';
        professionalPolicy: 'If the professional cancels before the service starts, the customer receives a full refund.';
        customerCutoffPolicy: 'Customer cancellation {hours} hours or more before the session: full refund. After that: no refund.';
        cutoffWindowLabel: '{hours}-hour refund window';
        timing: {
          beforeCutoff: 'This request is still before the {hours}-hour refund cutoff.';
          afterCutoff: 'This request is already past the {hours}-hour refund cutoff.';
          notApplicable: 'No refund cutoff applies to this order yet.';
        };
        outcomes: {
          none: 'No financial impact';
          void_pending_payment: 'Pending payment voided';
          full_refund: 'Full refund';
          no_refund: 'No refund';
          manual_refund_required: 'Manual refund review';
        };
        outcomeDescriptions: {
          none: 'No settled payment exists on this order yet.';
          void_pending_payment: 'Payment is still pending, so the order is simply closed.';
          full_refund: 'The payment should be refunded in full after cancellation.';
          no_refund: 'This cancellation is past the customer refund cutoff.';
          manual_refund_required: 'This payment needs manual refund handling.';
        };
        actorLabels: {
          customer: 'Customer';
          professional: 'Professional';
        };
        resolutionTitle: 'Cancellation summary';
        resolutionReasonLabel: 'Recorded reason';
        resolutionFinancialOutcomeLabel: 'Financial outcome';
        resolutionCancelledAtLabel: 'Closed at';
      };
      statusBanners: {
        requested: 'The provider is reviewing your request. We will notify you as soon as it is approved.';
        paid: 'Payment received. The provider will follow the selected schedule.';
        confirmed: 'Your schedule is confirmed. Please prepare the location and anything relevant before the session starts.';
        inService: 'The session is in progress. You can still send a message if anything else is needed.';
        cancelled: 'This reservation has been cancelled. You can book a new schedule anytime.';
        rejected: 'This request was declined. Try another slot or a different available provider.';
        expired: 'This request expired because the payment was not completed in time.';
      };
    };
    home: {
      emptyStateTitle: 'No active schedule yet';
      emptyStateDescription: 'Use the service catalog to start a new flow from discovery to booking.';
      emptyStateAction: 'Explore services';
    };
    serviceDetail: {
      highlightsTitle: 'Highlights';
    };
    professionalProfile: {
      storiesTitle: 'Activity stories';
      portfolioEntriesTitle: 'Service portfolio';
      galleryTitle: 'Practice gallery';
      testimonialsTitle: 'Family testimonials';
      feedbackTitle: 'Client feedback';
      credentialsTitle: 'Certification and compliance';
      recentActivityTitle: 'Recent activity';
      serviceSectionTitle: 'Choose a service';
      availabilityLabel: 'Availability';
      responseTimeLabel: 'Response time';
      languagesLabel: 'Languages';
      totalReviewsLabel: 'total reviews';
      recommendationLabel: 'Recommends';
      repeatClientsLabel: 'Returning clients';
    };
    professionalGender: {
      female: 'Female';
      male: 'Male';
    };
    explore: {
      genderOptions: {
        any: 'Any';
        female: 'Female';
        male: 'Male';
      };
    };
    review: {
      title: 'Leave a Review';
      titleTemplate: 'How was your session with {professionalName}?';
      helperText: 'Your review helps us improve service quality.';
      photoLabel: 'Add Photo (Optional)';
      photoButtonLabel: 'Add';
      reviewLabel: 'Tell us about your experience';
      reviewPlaceholder: 'The service was very friendly and professional...';
      submitLabel: 'Submit Review';
      uploadAlert: 'Photo upload simulation';
      successAlert: 'Review submitted successfully. Thank you for your feedback.';
    };
  };
  Integration: {
    eyebrow: 'Backend Integration';
    title: 'Backend Contract + Realtime Example';
    description: 'This page demonstrates REST access through the shared SDK generated from the backend OpenAPI document, plus realtime chat over WebSocket.';
    restSection: 'REST Contract';
    health: 'Health';
    frontendVersion: 'Frontend Version';
    professionals: 'Professionals';
    threads: 'Chat Threads';
    openapiLink: 'OpenAPI from backend';
    refresh: 'Refresh';
    restError: 'Failed to load backend data. Make sure the backend is running on localhost:8080.';
    socketSection: 'Realtime Chat';
    socketUrl: 'WebSocket URL';
    emptyMessages: 'No live messages yet. Send one message to verify the websocket flow.';
    messagePlaceholder: 'Send a live message to the backend demo thread...';
    socketError: 'WebSocket connection failed. Verify the backend websocket endpoint and allowed origin.';
    socketState: {
      idle: 'Idle';
      connecting: 'Connecting';
      connected: 'Connected';
      error: 'Error';
    };
    notesSection: 'Architecture Notes';
    noteContract: 'The OpenAPI document is exported from backend route registration, not hand-maintained in frontend.';
    noteSdk: 'Frontend integration uses the shared SDK package so fetch usage stays typed at development time.';
    noteWebsocket: 'Realtime chat is intentionally separated from OpenAPI because websocket transport needs its own event contract.';
  };
};
export default messages;
